export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_LIST_RESET = 'PRODUCT_LIST_RESET';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

export const PRODUCT_REVIEW_LIST_REQUEST = 'PRODUCT_REVIEW_LIST_REQUEST';
export const PRODUCT_REVIEW_LIST_SUCCESS = 'PRODUCT_REVIEW_LIST_SUCCESS';
export const PRODUCT_REVIEW_LIST_FAIL = 'PRODUCT_REVIEW_LIST_FAIL';

export const PRODUCT_REVIEW_LIST_ALL_REQUEST = 'PRODUCT_REVIEW_LIST_ALL_REQUEST';
export const PRODUCT_REVIEW_LIST_ALL_SUCCESS = 'PRODUCT_REVIEW_LIST_ALL_SUCCESS';
export const PRODUCT_REVIEW_LIST_ALL_FAIL = 'PRODUCT_REVIEW_LIST_ALL_FAIL';

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST';
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS';
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL';

export const PRODUCT_RANDOM_REQUEST = 'PRODUCT_RANDOM_REQUEST';
export const PRODUCT_RANDOM_SUCCESS = 'PRODUCT_RANDOM_SUCCESS';
export const PRODUCT_RANDOM_FAIL = 'PRODUCT_RANDOM_FAIL';
